module Contractions


# export 
export fix_contractions

"""
fix_contractions: Fix Contractions in a given text

params:
------
	- text:: AbstractString , given text
"""
function fix_contractions(text::AbstractString)
    text = replace.(text,"ain't"=>"am not")
    text = replace.(text,"aren't"=>"are not")
    text = replace.(text,"can't"=>"cannot")
    text = replace.(text,"can't've"=>"cannot have")
    text = replace.(text,"'cause"=>"because")
    text = replace.(text,"could've"=>"could have")
    text = replace.(text,"couldn't"=>"could not")
    text = replace.(text,"couldn't've"=>"could not have")
    text = replace.(text,"didn't"=>"did not")
    text = replace.(text,"doesn't"=>"does not")
    text = replace.(text,"don't"=>"do not")
    text = replace.(text,"hadn't"=>"had not")
    text = replace.(text,"hadn't've"=>"had not have")
    text = replace.(text,"hasn't"=>"has not")
    text = replace.(text,"haven't"=>"have not")
    text = replace.(text,"he'd"=>"he would")
    text = replace.(text,"he'd've"=>"he would have")
    text = replace.(text,"he'll"=>"he will")
    text = replace.(text,"he'll've"=>"he will have")
    text = replace.(text,"he's"=>"he is")
    text = replace.(text,"how'd"=>"how did")
    text = replace.(text,"how'd'y"=>"how do you")
    text = replace.(text,"how'll"=>"how will")
    text = replace.(text,"how's"=>"how is")
    text = replace.(text,"I'd"=>"I would")
    text = replace.(text,"I'd've"=>"I would have")
    text = replace.(text,"I'll"=>"I will")
    text = replace.(text,"I'll've"=>"I will have")
    text = replace.(text,"I'm"=>"I am")
    text = replace.(text,"I've"=>"I have")
    text = replace.(text,"isn't"=>"is not")
    text = replace.(text,"it'd"=>"it had")
    text = replace.(text,"it'd've"=>"it would have")
    text = replace.(text,"it'll"=>"it will")
    text = replace.(text,"it'll've"=>"it will have")
    text = replace.(text,"it's"=>"it is")
    text = replace.(text,"let's"=>"let us")
    text = replace.(text,"ma'am"=>"madam")
    text = replace.(text,"mayn't"=>"may not")
    text = replace.(text,"might've"=>"might have")
    text = replace.(text,"mightn't"=>"might not")
    text = replace.(text,"mightn't've"=>"might not have")
    text = replace.(text,"must've"=>"must have")
    text = replace.(text,"mustn't"=>"must not")
    text = replace.(text,"mustn't've"=>"must not have")
    text = replace.(text,"needn't"=>"need not")
    text = replace.(text,"needn't've"=>"need not have")
    text = replace.(text,"o'clock"=>"of the clock")
    text = replace.(text,"oughtn't"=>"ought not")
    text = replace.(text,"oughtn't've"=>"ought not have")
    text = replace.(text,"shan't"=>"shall not")
    text = replace.(text,"sha'n't"=>"shall not")
    text = replace.(text,"shan't've"=>"shall not have")
    text = replace.(text,"she'd"=>"she would")
    text = replace.(text,"she'd've"=>"she would have")
    text = replace.(text,"she'll"=>"she will")
    text = replace.(text,"she'll've"=>"she will have")
    text = replace.(text,"she's"=>"she is")
    text = replace.(text,"should've"=>"should have")
    text = replace.(text,"shouldn't"=>"should not")
    text = replace.(text,"shouldn't've"=>"should not have")
    text = replace.(text,"so've"=>"so have")
    text = replace.(text,"so's"=>"so is")
    text = replace.(text,"that'd"=>"that would")
    text = replace.(text,"that'd've"=>"that would have")
    text = replace.(text,"that's"=>"that is")
    text = replace.(text,"there'd"=>"there had")
    text = replace.(text,"there'd've"=>"there would have")
    text = replace.(text,"there's"=>"there is")
    text = replace.(text,"they'd"=>"they would")
    text = replace.(text,"they'd've"=>"they would have")
    text = replace.(text,"they'll"=>"they will")
    text = replace.(text,"they'll've"=>"they will have")
    text = replace.(text,"they're"=>"they are")
    text = replace.(text,"they've"=>"they have")
    text = replace.(text,"to've"=>"to have")
    text = replace.(text,"wasn't"=>"was not")
    text = replace.(text,"we'd"=>"we had")
    text = replace.(text,"we'd've"=>"we would have")
    text = replace.(text,"we'll"=>"we will")
    text = replace.(text,"we'll've"=>"we will have")
    text = replace.(text,"we're"=>"we are")
    text = replace.(text,"we've"=>"we have")
    text = replace.(text,"weren't"=>"were not")
    text = replace.(text,"what'll"=>"what will")
    text = replace.(text,"what'll've"=>"what will have")
    text = replace.(text,"what're"=>"what are")
    text = replace.(text,"what's"=>"what is")
    text = replace.(text,"what've"=>"what have")
    text = replace.(text,"when's"=>"when is")
    text = replace.(text,"when've"=>"when have")
    text = replace.(text,"where'd"=>"where did")
    text = replace.(text,"where's"=>"where is")
    text = replace.(text,"where've"=>"where have")
    text = replace.(text,"who'll"=>"who will")
    text = replace.(text,"who'll've"=>"who will have")
    text = replace.(text,"who's"=>"who is")
    text = replace.(text,"who've"=>"who have")
    text = replace.(text,"why's"=>"why is")
    text = replace.(text,"why've"=>"why have")
    text = replace.(text,"will've"=>"will have")
    text = replace.(text,"won't"=>"will not")
    text = replace.(text,"won't've"=>"will not have")
    text = replace.(text,"would've"=>"would have")
    text = replace.(text,"wouldn't"=>"would not")
    text = replace.(text,"wouldn't've"=>"would not have")
    text = replace.(text,"y'all"=>"you all")
    text = replace.(text,"y'alls"=>"you alls")
    text = replace.(text,"y'all'd"=>"you all would")
    text = replace.(text,"y'all'd've"=>"you all would have")
    text = replace.(text,"y'all're"=>"you all are")
    text = replace.(text,"y'all've"=>"you all have")
    text = replace.(text,"you'd"=>"you had")
    text = replace.(text,"you'd've"=>"you would have")
    text = replace.(text,"you'll"=>"you you will")
    text = replace.(text,"you'll've"=>"you you will have")
    text = replace.(text,"you're"=>"you are")
    text = replace.(text,"you've"=>"you have")
    return text
end





end
